### PR TITLE
[apcupsd_exporter] add apcupsd_exporter

### PR DESCRIPTION
**Pull request by stefancrain**
I know this is not essential to k8s, but there is not a single arm64 version of this on docker hub.

### CODE REVIEW

**Comment by onedr0p** [comment]
Looks great, thanks!

**Comment by xUnholy** [comment]
Absolutely fantastic work, if this is an upstream could you also add it to the schedule workflow so we can build and maintain their latest releases also?

**Comment by onedr0p** [comment]
Sadly they don't version their releases, @stefancrain used the most recent git tag.

**Comment by stefancrain** [comment]
Sadly correct, adding this here incase they suddenly start versioning https://github.com/mdlayher/apcupsd_exporter/releases

**Comment by stefancrain** [comment]
I'll see if I can get the schedule workflow to update the version file with the latest SHA :-)

**Comment by xUnholy** [comment]
Thanks @stefancrain - if it's difficult can always raise an issue and we'll tackle it when they support official releases, however, the SHA definitely should work also! Good work 👍

**Pull request merged**
