### PR TITLE
Update buildx version; deprecate k8s-sidecar

### LINKED ISSUE #150: Update GH action for buildx
We are a couple versions behind...

https://github.com/crazy-max/ghaction-docker-buildx/releases

### PR DESCRIPTION
**Pull request by xUnholy**
# Description

Updating `buildx` github actions to use v3 with latest stability and testing.

Deprecating k8s-sidecar due to upstream support.

## Type Of Change

To help us figure out who should review this PR, please put an X in all the areas that this PR affects.

- [ ] Docs
- [x] Installation
- [x] Performance and Scalability
- [ ] Security
- [ ] Test and/or Release
- [ ] User Experience

## Issue Ref (Optional)

Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #150

## Notes

Add special notes for your reviewer here.

### CODE REVIEW

**Comment by onedr0p** [comment]
Did you want to deprecate ghostunnel as well? Otherwise looks good.

**Comment by xUnholy** [comment]
@onedr0p I was looking into ghostunnel, I didn't see their new image that is multi-arch though, only saw the PR was merged, not sure if it has been released with a new version as of yet.

**Comment by xUnholy** [comment]
@easimon I've noticed that kustomize is having issues, it looks like it's failing on the amd64 variant to build, did you test this architecture? Alternatively, we could disable it here, but if you could PTAL that would be awesome 🙏

**Comment by easimon** [comment]
Hm... The logs say it did not find kustomize/v3.3.1. 

kustomize switched their tag naming at some point, since the same repo is hosting other artifacts (kyaml e.g.).
So the build failed because it was trying to check out an old version (v.3.3.1) with the new naming scheme (like kustomize/v3.8.2).

Not sure where the build picks this version number from.

**Pull request merged**
