### PR TITLE
fix kustomize version auto-upgrade

### LINKED ISSUE #159: "Version" docker tags broken for many images
# Details

A recent refactoring on the docker build introduced a typo in most of the build workflows (missing colon).

The push step pushes e.g. `docker.io/raspbernetes/kustomizev3.8.2`, and since missing tags are replaced by `:latest`, 
this results in docker images named e.g. `docker.io/raspbernetes/kustomizev3.8.2:latest`.

But there seems to be another issue for the `latest` tag, since `docker.io/raspbernetes/kustomize:latest` does not seem to contain the latest version (neither docker.io/raspbernetes/kustomizev3.8.2:latest nor docker.io/raspbernetes/kustomize:v3.8.2, but something else).

**What steps did you take and what happened:**

Take a look at the following kustomize version outputs:

```
$ docker run docker.io/raspbernetes/kustomize:v3.8.2 kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-09-14T09:28:56UTC GoOs:linux GoArch:amd64}

$ docker run docker.io/raspbernetes/kustomizev3.8.2:latest kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-09-14T09:28:56UTC GoOs:linux GoArch:amd64}

$ docker run docker.io/raspbernetes/kustomize:latest kustomize version
Version: {Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
```

**What did you expect to happen:**

- Version tags should be created correctly
- kustomize:latest should correspond to the same binary as v3.8.2

**Anything else you would like to add:**

MR for the :version tag is incoming, but no idea what's wrong with the latest tag.

### PR DESCRIPTION
**Pull request by easimon**
# Description

Change version scraping for kustomize in auto-upgrade workflow, make it compatible with their current release / tag scheme.

## Type Of Change

To help us figure out who should review this PR, please put an X in all the areas that this PR affects.

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] Test and/or Release
- [ ] User Experience

## Issue Ref (Optional)

Fixes #159

## Notes

Quite simplistic approach, which might not be rock solid (see comments in the code), but should do the trick for now.

### CODE REVIEW

**Comment by easimon** [comment]
I did not include the manual version upgrade in kustomize on purpose this time... If I fixed the auto-upgrade, the next schedule should do the trick.

**Comment by xUnholy** [comment]
I'll deploy the schedule after we merged and we'll see how it responds to these changes as I don't have a method for running them out of band on a feature branch.

**Comment by easimon** [comment]
Seems like it worked :)

**Comment by xUnholy** [comment]
Yep brilliant work @easimon 👍

**Pull request merged**
