### PR TITLE
Prometheus operator

### PR DESCRIPTION
**Pull request by HaveFun83**
This PR should address #61

Prometheus-operator k8s deployment contain three images:
jimmidyson/configmap-reload  is already a multi-arch build.

The prometheus-config-reloader and prometheus-operator is addressed here.

Please have a look. Thx

### CODE REVIEW

**Comment by xUnholy** [comment]
Just gave it a trial run, appears the job that starts first fails - I'll leave it with you to find all the dependencies reach out over discord if you need help.

**Comment by HaveFun83** [comment]
@xUnholy can you give me some more debug infos? Which job? I searched around in the github actions logs but saw nothing suspicious.

**Comment by xUnholy** [comment]
@HaveFun83 

The pod was `prometheus-operator-admission-create-j48qz` which uses the image `jettech/kube-webhook-certgen:v1.0.0`

**Comment by xUnholy** [comment]
Which is strange because this is what is being deployed

`image: jettech/kube-webhook-certgen:v1.0.0`

Although, the helm chart specifies https://github.com/helm/charts/blob/a93cb4a709ae0840b47215f9c3ca3e1d0e5d7764/stable/prometheus-operator/values.yaml#L1093... 🤷‍♂️

**Comment by xUnholy** [comment]
Fixed it by updating the helm chart `version: 8.13.2`.

```
k get pods
NAME                                                      READY   STATUS                  RESTARTS   AGE
prometheus-operator-grafana-66d49fd6d7-6q4qg              0/2     Init:CrashLoopBackOff   2          95s
prometheus-operator-kube-state-metrics-7f979567df-2dhdd   0/1     CrashLoopBackOff        3          95s
prometheus-operator-operator-76565688b9-pvtfw             0/2     CrashLoopBackOff        6          95s
prometheus-operator-prometheus-node-exporter-9vqwq        1/1     Running                 0          95s
prometheus-operator-prometheus-node-exporter-fpjv5        1/1     Running                 0          95s
prometheus-operator-prometheus-node-exporter-jtls7        1/1     Running                 0          95s
prometheus-operator-prometheus-node-exporter-tqk47        1/1     Running                 0          95s
```

**Comment by xUnholy** [comment]
The following need to be also multi-arch

```
image: kiwigrid/k8s-sidecar:0.1.99
name: grafana-sc-dashboard
```

```
image: quay.io/coreos/kube-state-metrics:v1.9.5
name: kube-state-metrics
```

**Comment by xUnholy** [comment]
Found this interesting https://github.com/carlosedp/cluster-monitoring

**Comment by HaveFun83** [comment]
Ah now i got you. Yes the prometheus-operator helm-chart has some more dependencies build in but the plain operator [prometheus-operator#quickstart](https://github.com/coreos/prometheus-operator#quickstart) should work now. I will try to get some time to look at the dependencies this week.

We should also have a look at some testing piplines? 
How can i get in touch via discord?

**Comment by xUnholy** [comment]
Yep, join the discord and shoot me some messages and we can throw some ideas around.

**Pull request merged**
